---

- name: Ensure yum-managed version of awscli is removed
  yum:
    name: awscli
    state: absent

- name: Ensure dependencies are installed
  yum:
    name: [glibc, groff, less, unzip]
    state: present

- name: Create temporary working directory for installing awscli
  file:
    path: /tmp/awscli-v2
    state: directory
    owner: root
    group: wheel
    mode: 0755

- name: Download and unarchive awscli version 2 zip file
  unarchive:
    src: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-{{ awscli_version }}.zip"
    dest: /tmp/awscli-v2
    owner: root
    group: wheel

# This task is necessary to ensure the task that actually installs
# awscli (the next task) doesn't fail and cause the role to exit
# without completing. Another method would have been to ignore
# the failures, but I'm not so sure that's a good idea.
- name: Check to see if awscli version 2 is already installed
  command: /usr/local/bin/aws --version
  register: awscliv2_present
  changed_when: false

- name: Install awscli version 2 if not already present
  command: /tmp/awscli-v2/aws/install
  when: awscliv2_present.rc == "0"

- name: Ensure symlinks can reach the aws binaries
  file:
    path: /usr/local/aws-cli/v2/current/dist
    state: directory
    mode: 0755
